name: Cool

on:
  pull_request:
    branches:
      - '**'

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"